### ISSUE TITLE
Meta-analaysis of all predicted targets for these 120 products.

### ISSUE THREAD

**Issue by IVANDOMENZAIN** [SysBioChalmers/CellFactory-yeast-GEM#9]
- [x] Group of products based on tSNE using the predicted genes strategies.

- [ ] compare the gene targets from a general minimal condition and the in vivo experimental condition. -> generate venn diagrams comparing predictions with and without background

- [x] compare the general trends using the output from step2 and step3
